prosopon: include/prosopon/macros.h File Reference
include/prosopon/macros.h File Reference
A collection of macros to ease performing common prosopon functions.
#include <prosopon/prosopon.h>
#include <prosopon/lib/std.h>
#include <string.h>
Functions
static int pro_match_actor_type (pro_state_ref s, pro_ref t, pro_actor_type type)
static int pro_match_type (pro_state_ref s, pro_ref t, pro_type type)
static void pro_list_append_inplace (pro_state_ref s, pro_ref *msg, pro_ref val)
Detailed Description
A collection of macros to ease performing common prosopon functions.
Function Documentation
static void pro_list_append_inplace (pro_state_ref s, pro_ref * msg, pro_ref val) [inline, static]
Appends an object to a list and returns the modified reference.
References PRO_EMPTY_REF, pro_list_append(), and pro_release().
static int pro_match_actor_type (pro_state_ref s, pro_ref t, pro_actor_type type) [inline, static]
Is an actor of a given actor type?
Returns:
1 if true, else 0
References pro_get_actor_type().
static int pro_match_type (pro_state_ref s, pro_ref t, pro_type type) [inline, static]
Is an object of a given type?
Returns:
1 if true, else 0
References pro_get_type().